version: 0.0
os: linux

files:
  - source: .
    destination: /home/ec2-user/app/zip/
    overwrite: yes

permissions:
  - object: /home/ec2-user/app/zip/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755  # 실행 권한 추가 (start.sh, stop.sh 포함)

hooks:
  AfterInstall:
    - location: stop.sh  # 상대 경로 사용
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: start.sh
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh
      timeout: 60
      runas: ec2-user
