spring:
  profiles:
    active: prod

  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: true

  jwt:
    secret: ${JWT_SECRET}

openai:
  api:
    key: ${OPEN_AI_API_KEY}

security:
  oauth2:
    client:
      registration:
        google:
          client-name: google
          client-id: ${GOOGLE_CLIENT_ID}
          client-secret: ${GOOGLE_CLIENT_SECRET}
          redirect-uri: ${GOOGLE_REDIRECT_URI}
          authorization-grant-type: authorization_code
          scope: profile, email

cloud:
  aws:
    s3:
      bucketName: ${AWS_S3_BUCKET_NAME}
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false

servlet:
  multipart:
    max-file-size: 50MB
    max-request-size: 50MB
